### ISSUE TITLE
Cammunda integartion with keycloak SSO Jar Depenedency cannot be resolved

### ISSUE THREAD

**Issue by raulkozy** [VonDerBeck/camunda-identity-keycloak#5]
The dependency as provided cannot be resolved.
it seems that the remote location of the source has been changed or does not exist at this point in time.
kindly provide us with the new location or updates jar if any.
 
```
<dependency>
<groupId>de.vonderbeck.bpm.identity</groupId>
<artifactId>camunda-identity-keycloak</artifactId>
<version>0.6.1-SNAPSHOT</version>
</dependency>
```

please help us to integrate camunda with keycloak for sso.

**Comment by vojkog** [comment]
I think that plugin is not in maven-central (yet).
You can install it in your local maven repo.

**Comment by raulkozy** [comment]
Hi @vojkog 

we already tried building it over the local maven repo, but
Building the project locally leads to the no manifest file attribute . I want to know that how will this project runs which will integrate SSO of camunda with keycloak . How will the project jar will be added to the server so that the internal code will be called.
Please help as it is not mentioned in ReadMe.md file. Next i have checked with the keycloak-showcase-master repository where the jar cannot be build .

**Comment by vojkog** [comment]
Hi @rahulkohli23 ,
Have you tried:
``` mvn clean install -DskipTests```
After that dependency should be in your local repo:
```.m2\repository\de\vonderbeck\bpm\identity\camunda-identity-keycloak\0.6.1-SNAPSHOT\ ```

**Comment by raulkozy** [comment]
@vojkog 
We Appreciate your response. but we are done with this step
and below is the screenshot of the terminal window explaining what happens when we try to execute the jar obtained.

![image](https://user-images.githubusercontent.com/40965683/61049033-14a83000-a401-11e9-9960-bf041792830c.png)

Kindly provide us a way through it.
also, provide us with the next set of steps to be followed after this jar works.

**Comment by vojkog** [comment]
Hi, I see where the misunderstanding is. This jar is not meant to be executable.
So I think this is not a "Dependency cannot be resolved" issue.

As a next step, I can only point you to existing documentation of how to **include** the jar into **your** project https://github.com/VonDerBeck/camunda-identity-keycloak#usage-with-camunda-spring-boot

**Comment by raulkozy** [comment]
Hi @vojkog ,
can u clone the project and run it on your machine and let us know if are able to get the specified output of camunda to keycloak sso

**Comment by raulkozy** [comment]
Hi @vojkog ,
I thanks for your contribution.
was able to implement the SSO with the following project.

https://github.com/VonDerBeck/camunda-showcase-keycloak/
